name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
  pull_request:

permissions:
  contents: read

jobs:
  test-android:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Test
        run: ./gradlew allTests --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/

  test-ios:
    runs-on: macos-latest-xlarge
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          select-xcode-26: "true"

      - name: Test
        run: ./gradlew iosSimulatorArm64Test macosArm64Test -Pkotlin.incremental.native=false --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/

  test-jvm:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Test
        run: ./gradlew jvmTest --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/


  binary-compatibility-check:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: API check
        run: ./gradlew apiCheck --stacktrace --show-version --continue

  ktfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: ktfmt
        run: ./gradlew ktlintCheck --stacktrace --show-version --continue

  detekt:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Detekt
        run: ./gradlew detekt --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/

  publish-maven-local:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-action
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal --stacktrace --show-version --no-configuration-cache